[package]
name = "ra-common"
version = "0.1.0"
authors = ["Natnatee Dokmai <ndokmai@indiana.edu>"]
edition = "2018"

[dependencies]
byteorder = "=1.3.2"
serde = { version = "=1.0", features = ["derive"] }
serde_cbor = "=0.10.2"
serde-big-array = "=0.2.0"
sgx-crypto = { path = "../sgx-crypto" }

